<a href="https://colab.research.google.com/github/Aron151281/Aron151281/blob/main/turma_VamoAi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# < font color = orange> series

In [ ]:
import pandas as pd

In [ ]:
- series sao objetos unidimensonais  (arrays) contendo dados e labels (ou index)

## Formas de criação de series

In [ ]:
s = pd.Series(list('abcdef'))
s

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [ ]:
s = pd.Series([2,4,6,8])
s

0    2
1    4
2    6
3    8
dtype: int64

### o index pode ser especificado

In [ ]:
s = pd.Series([2,4,6,8], index =['f', 'a', 'c', 'e'])
s

f    2
a    4
c    6
e    8
dtype: int64

### o valor pode  ser selecionado pelo seu index

In [ ]:
s['a']

4

### assim como multiplos valores podem ser selecionados

In [ ]:
s[['a', 'e']]

a    4
e    8
dtype: int64

### os indices nao precisam ser valores unicos

In [ ]:
s2 = pd.Series(range(4), index = list('abab'))
s2

a    0
b    1
a    2
b    3
dtype: int64

In [ ]:
s2['b']

b    1
b    3
dtype: int64

In [ ]:
s2['b'][1]

3

### series suportam operações de filtragem

In [ ]:
s

f    2
a    4
c    6
e    8
dtype: int64

In [ ]:
s>4

f    False
a    False
c     True
e     True
dtype: bool

### podemos realizar tambem operações aritimeticas

In [ ]:
s+4

f     6
a     8
c    10
e    12
dtype: int64

In [ ]:
s*4

f     8
a    16
c    24
e    32
dtype: int64

In [ ]:
dicionario = {'b':100, 'c':150,'d':200}
s = pd.Series(dicionario)
s

b    100
c    150
d    200
dtype: int64

### series suportam variaveis nulas

In [ ]:
s = pd.Series(dicionario, index = list('abcd'))
s

a      NaN
b    100.0
c    150.0
d    200.0
dtype: float64

### é possivel realizar operacoes aritimerticas entre duas series

In [ ]:
s2 = pd.Series([1,2,3], index = ['c','b','a'])
s2

c    1
b    2
a    3
dtype: int64

In [ ]:
s*s2

a      NaN
b    200.0
c    150.0
d      NaN
dtype: float64

In [ ]:
s+s2

a      NaN
b    102.0
c    151.0
d      NaN
dtype: float64

### atividade

In [ ]:
primeira = pd.Series

# NumPy

### um array Numpy é uma tabela multimensional de elemnetos do mesmo tipo , indexado por uma tupla de inteiros

In [ ]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5]
lista

[1, 2, 3, 4, 5]

### com a lista criada vamos convertela em um array numpay

In [ ]:
meu_array = np.array(lista)
meu_array

array([1, 2, 3, 4, 5])

### Type retorna o tipo da variavel

In [ ]:
type(meu_array)

numpy.ndarray

### atributo dtype mpostra os tipos dos elementos contidos array

In [ ]:
meu_array.dtype

dtype('int64')

### o atributo shape retorna uma tupla onde cada indice tera o numero de elementos correspondentes, indicando a forma daquele array

In [ ]:
meu_array.shape

(5,)

In [ ]:
meu_array[1]

2

## maneiras de criar arrays

In [ ]:
# passando os valores
array1 = np.array([(1.5,2,3),(4,5,6)])
array1

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
array1.shape

(2, 3)

In [ ]:
array1.dtype

dtype('float64')

In [ ]:
# usando a função zeros
array2 = np.zeros((2,3))
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# usando a função ones
array3 = np.ones((2,3,4))
array3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# usando o estado de memoria
array4 = np.empty((2,3))
array4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# usando a função arange
array5 = np.arange(10,30,5)
array5

array([10, 15, 20, 25])

In [ ]:
# usando a função random ( numeros aleatorios)
array6 = np.random.rand(3,2)
array6

array([[0.8076105 , 0.85889967],
       [0.90850314, 0.75022598],
       [0.5907038 , 0.27850986]])

### operações uteis para manipulações de dados

In [ ]:
array_teste = np.array([(8.5,5,6,5),(4,9,12,2.5),(20,3,3,14.2)])
array_teste

array([[ 8.5,  5. ,  6. ,  5. ],
       [ 4. ,  9. , 12. ,  2.5],
       [20. ,  3. ,  3. , 14.2]])

In [ ]:
#operações matematicas
array_teste - 2

array([[ 6.5,  3. ,  4. ,  3. ],
       [ 2. ,  7. , 10. ,  0.5],
       [18. ,  1. ,  1. , 12.2]])

In [ ]:
# slice ( parecido com as listas )
array_teste[:2]

array([[ 8.5,  5. ,  6. ,  5. ],
       [ 4. ,  9. , 12. ,  2.5]])

In [ ]:
array_teste.shape

(3, 4)

In [ ]:
# podemos redefinir o formato do array ( muito util quando o formato nao é compativel)
array_teste.reshape((2,6))

array([[ 8.5,  5. ,  6. ,  5. ,  4. ,  9. ],
       [12. ,  2.5, 20. ,  3. ,  3. , 14.2]])

In [ ]:
# separar o array em multiplos sub-array
array_separados=np.split(array_teste,3)
array_separados

[array([[8.5, 5. , 6. , 5. ]]),
 array([[ 4. ,  9. , 12. ,  2.5]]),
 array([[20. ,  3. ,  3. , 14.2]])]

In [ ]:
# é possivel juntar os arrays
array_unico = np.concatenate(array_separados)
array_unico

array([[ 8.5,  5. ,  6. ,  5. ],
       [ 4. ,  9. , 12. ,  2.5],
       [20. ,  3. ,  3. , 14.2]])

### operaçoes semelhantes com pandas

podemos calcular estatisticas dos arrays semelhantes ao pandas

In [ ]:
array_teste

array([[ 8.5,  5. ,  6. ,  5. ],
       [ 4. ,  9. , 12. ,  2.5],
       [20. ,  3. ,  3. , 14.2]])

In [ ]:
array_teste.max()

20.0

In [ ]:
array_teste.min()

2.5

In [ ]:
array_teste.sum()

92.2

In [ ]:
array_teste.mean()

7.683333333333334

### pandas e numpy

In [ ]:
import pandas as pd

In [ ]:
vingadores=['thor','hulk','homem de ferro','miranha']
vingadores

['thor', 'hulk', 'homem de ferro', 'miranha']

In [ ]:
type(vingadores)

list

### criar um array numpy a partir de uma lista vingadores

In [ ]:
array_vingadores = np.array(vingadores)
array_vingadores

array(['thor', 'hulk', 'homem de ferro', 'miranha'], dtype='<U14')

In [ ]:
type(array_vingadores)

numpy.ndarray

In [ ]:
# converter o array para series
array_to_series = pd.Series(array_vingadores)
array_to_series

0              thor
1              hulk
2    homem de ferro
3           miranha
dtype: object

In [ ]:
# converter uma series para um array (função.to_numpy())
series_to_array = array_to_series.to_numpy()
series_to_array

array(['thor', 'hulk', 'homem de ferro', 'miranha'], dtype=object)

In [ ]:
array_exercicio = np.array((10,20,30,40,50,60,70))
array_exercicio

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
array_sub = array_exercicio - 5
array_sub

array([ 5, 15, 25, 35, 45, 55, 65])

In [ ]:
array_to_pandas = pd.Series(array_sub)
array_to_pandas

0     5
1    15
2    25
3    35
4    45
5    55
6    65
dtype: int64

### Dataframe

- dataframes são como planilhas , uma estrutura de dados contendo uma coleção de colunas.
- ele possui linhas e colunas.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6]], columns = ['col1','col2','col3'])
df

   col1  col2  col3
0     1     2     3
1     4     5     6

### cirando um DataFrame a partir de um array

In [ ]:
array_criado = np.array([[0,1,2],[3,4,5]])
array_criado

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
dataframe= pd.DataFrame(array_criado, columns = ['col1','col2','col3'])
dataframe

   col1  col2  col3
0     0     1     2
1     3     4     5

##  criando um dataframe a partir de um dicionario

In [ ]:
dados = {'flamengo':[56,72,90,71,71],'palmeiras':[63,80,74,58,66], 'corintia':[72,44,56,51,57]}
fut = pd.DataFrame(dados,index = [2017,2018,2019,2020,2021])
fut

      flamengo  palmeiras  corintia
2017        56         63        72
2018        72         80        44
2019        90         74        56
2020        71         58        51
2021        71         66        57

In [ ]:
#as colunas podem ser retornadas como uma series
fut['palmeiras']

2017    63
2018    80
2019    74
2020    58
2021    66
Name: palmeiras, dtype: int64

In [ ]:
#o atributo values retorna os dados contidos no DataFrame como um array bidimensional
fut.values

array([[56, 63, 72],
       [72, 80, 44],
       [90, 74, 56],
       [71, 58, 51],
       [71, 66, 57]])

In [ ]:
fut['flamengo'].values

array([56, 72, 90, 71, 71])

In [ ]:
#criação de uma nova coluna no valores
fut['nova_coluna'] = np.NaN
fut

      flamengo  palmeiras  corintia  nova_coluna
2017        56         63        72          NaN
2018        72         80        44          NaN
2019        90         74        56          NaN
2020        71         58        51          NaN
2021        71         66        57          NaN

In [ ]:
#inverter a coluna
fut.T

             2017  2018  2019  2020  2021
flamengo     56.0  72.0  90.0  71.0  71.0
palmeiras    63.0  80.0  74.0  58.0  66.0
corintia     72.0  44.0  56.0  51.0  57.0
nova_coluna   NaN   NaN   NaN   NaN   NaN

In [ ]:
# renomear as colunas
fut.rename(columns={'corintia':'timao'})

      flamengo  palmeiras  timao  nova_coluna
2017        56         63     72          NaN
2018        72         80     44          NaN
2019        90         74     56          NaN
2020        71         58     51          NaN
2021        71         66     57          NaN

In [ ]:
#reatribuindo
fut = fut.rename(columns={'nova_coluna':'PSG'})

In [ ]:
fut

      flamengo  palmeiras  corintia  PSG
2017        56         63        72  NaN
2018        72         80        44  NaN
2019        90         74        56  NaN
2020        71         58        51  NaN
2021        71         66        57  NaN

In [ ]:
fut.rename(columns={'psg': 'real'},inplace = True )

In [ ]:
fut

      flamengo  palmeiras  corintia  PSG
2017        56         63        72  NaN
2018        72         80        44  NaN
2019        90         74        56  NaN
2020        71         58        51  NaN
2021        71         66        57  NaN

In [ ]:
fut['palmeiras_multiplicada'] = fut['palmeiras']*2
fut

      flamengo  palmeiras  corintia  PSG  palmeiras_multiplicada
2017        56         63        72  NaN                     126
2018        72         80        44  NaN                     160
2019        90         74        56  NaN                     148
2020        71         58        51  NaN                     116
2021        71         66        57  NaN                     132

### alguns calculos estatisticos

In [ ]:
fut.describe()

        flamengo  palmeiras   corintia
count   5.000000   5.000000   5.000000
mean   72.000000  68.200000  56.000000
std    12.062338   8.786353  10.319884
min    56.000000  58.000000  44.000000
25%    71.000000  63.000000  51.000000
50%    71.000000  66.000000  56.000000
75%    72.000000  74.000000  57.000000
max    90.000000  80.000000  72.000000

In [ ]:
fut.sum()

flamengo     360
palmeiras    341
corintia     280
dtype: int64

In [ ]:
fut.sum(axis='columns')

2017    191
2018    196
2019    220
2020    180
2021    194
dtype: int64

In [ ]:
fut.min()

flamengo                   56.0
palmeiras                  58.0
corintia                   44.0
PSG                         NaN
palmeiras_multiplicada    116.0
dtype: float64

In [ ]:
fut.max()

flamengo                   90.0
palmeiras                  80.0
corintia                   72.0
PSG                         NaN
palmeiras_multiplicada    160.0
dtype: float64

In [ ]:
fut.std()

flamengo                  12.062338
palmeiras                  8.786353
corintia                  10.319884
PSG                             NaN
palmeiras_multiplicada    17.572706
dtype: float64

In [ ]:
fut.median()

flamengo     71.0
palmeiras    66.0
corintia     56.0
dtype: float64

In [ ]:
fut.isnull()

      flamengo  palmeiras  corintia   PSG  palmeiras_multiplicada
2017     False      False     False  True                   False
2018     False      False     False  True                   False
2019     False      False     False  True                   False
2020     False      False     False  True                   False
2021     False      False     False  True                   False

In [ ]:
import pandas as pd
import numpy as np

- pandas carrega varios tipos de dados como csv , json , xml , html e excel.

In [ ]:
url = 'https://raw.githubusercontent.com/parvathy-nsarma/Walmart-Data/main/Walmart_Store_sales.csv'
walmart = pd.read_csv(url)
walmart

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [ ]:
walmart[:10]['Weekly_Sales']

0    1643690.90
1    1641957.44
2    1611968.17
3    1409727.59
4    1554806.68
5    1439541.59
6    1472515.79
7    1404429.92
8    1594968.28
9    1545418.53
Name: Weekly_Sales, dtype: float64

In [ ]:
walmart.loc[0]['Date']

'05-02-2010'

In [ ]:
walmart[:1]['Date']

0    05-02-2010
Name: Date, dtype: object

In [ ]:
walmart.iloc[0,1]

'05-02-2010'

In [ ]:
walmart.loc[0]

Store                    1
Date            05-02-2010
Weekly_Sales     1643690.9
Holiday_Flag             0
Temperature          42.31
Fuel_Price           2.572
CPI             211.096358
Unemployment         8.106
Name: 0, dtype: object

In [ ]:
walmart.loc[[1,3,4]]['Date']

1    12-02-2010
3    26-02-2010
4    05-03-2010
Name: Date, dtype: object

In [ ]:
walmart.loc[(walmart['Temperature'] > 90) & (walmart ['Store']==1)]

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
78,1,05-08-2011,1624383.75,0,91.65,3.684,215.544618,7.962
79,1,12-08-2011,1525147.09,0,90.76,3.638,215.605788,7.962

### função query
- é possivel realizar consultas por coluna e por index

In [ ]:
walmart.query('Weekly_Sales > 1624383.75')

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
42,1,26-11-2010,1955624.11,1,64.52,2.735,211.748433,7.838
44,1,10-12-2010,1682614.26,0,46.33,2.843,211.465953,7.838
45,1,17-12-2010,1891034.93,0,49.84,2.869,211.405312,7.838
...,...,...,...,...,...,...,...,...
5766,41,24-12-2010,2225016.73,0,29.81,2.781,191.143019,7.508
5814,41,25-11-2011,1906713.35,1,36.37,3.424,195.770400,6.759
5817,41,16-12-2011,1682368.32,0,25.01,3.266,195.984169,6.759
5818,41,23-12-2011,2263722.68,0,25.59,3.173,196.171389,6.759
6338,45,24-12-2010,1682862.03,0,30.59,3.141,182.544590,8.724

In [ ]:
walmart.query('Weekly_Sales > 1624383.75')

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
42,1,26-11-2010,1955624.11,1,64.52,2.735,211.748433,7.838
44,1,10-12-2010,1682614.26,0,46.33,2.843,211.465953,7.838
45,1,17-12-2010,1891034.93,0,49.84,2.869,211.405312,7.838
...,...,...,...,...,...,...,...,...
5766,41,24-12-2010,2225016.73,0,29.81,2.781,191.143019,7.508
5814,41,25-11-2011,1906713.35,1,36.37,3.424,195.770400,6.759
5817,41,16-12-2011,1682368.32,0,25.01,3.266,195.984169,6.759
5818,41,23-12-2011,2263722.68,0,25.59,3.173,196.171389,6.759
6338,45,24-12-2010,1682862.03,0,30.59,3.141,182.544590,8.724

In [ ]:
walmart.query('1 <= index < 7')

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,211.380643,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,211.215635,8.106

In [ ]:
walmart.query('35<=Temperature<50')

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6398,45,17-02-2012,858853.75,0,36.85,3.695,189.842483,8.424
6399,45,24-02-2012,753060.78,0,42.86,3.739,190.006988,8.424
6400,45,02-03-2012,782796.01,0,41.55,3.816,190.171493,8.424
6401,45,09-03-2012,776968.87,0,45.52,3.848,190.335997,8.424
6405,45,06-04-2012,899479.43,0,49.73,3.996,190.685171,8.567

In [ ]:
val = 1643690.90
walmart.query('Weekly_Sales > @val')

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
42,1,26-11-2010,1955624.11,1,64.52,2.735,211.748433,7.838
44,1,10-12-2010,1682614.26,0,46.33,2.843,211.465953,7.838
45,1,17-12-2010,1891034.93,0,49.84,2.869,211.405312,7.838
46,1,24-12-2010,2387950.20,0,52.33,2.886,211.405122,7.838
53,1,11-02-2011,1649614.93,1,36.39,3.022,212.936705,7.742
...,...,...,...,...,...,...,...,...
5766,41,24-12-2010,2225016.73,0,29.81,2.781,191.143019,7.508
5814,41,25-11-2011,1906713.35,1,36.37,3.424,195.770400,6.759
5817,41,16-12-2011,1682368.32,0,25.01,3.266,195.984169,6.759
5818,41,23-12-2011,2263722.68,0,25.59,3.173,196.171389,6.759
6338,45,24-12-2010,1682862.03,0,30.59,3.141,182.544590,8.724

In [ ]:
walmart.query('Store in [44,45]')

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6149,44,05-02-2010,281090.95,0,31.53,2.666,126.442065,8.119
6150,44,12-02-2010,286857.13,1,33.16,2.671,126.496258,8.119
6151,44,19-02-2010,267956.30,0,35.70,2.654,126.526286,8.119
6152,44,26-02-2010,273079.07,0,29.98,2.667,126.552286,8.119
6153,44,05-03-2010,284617.27,0,40.65,2.681,126.578286,8.119
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [ ]:
url2 = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
titanic = pd.read_csv(url2)
titanic

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [ ]:
titanic.loc[[2,3,4]]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.925
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.100
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.050

In [ ]:
titanic.query('Age < 30')

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
...,...,...,...,...,...,...,...,...
880,0,3,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000

In [ ]:
titanic.query('Pclass == 3')

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
...,...,...,...,...,...,...,...,...
878,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
880,0,3,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

## outras operações

In [ ]:
df_aux = walmart.copy()
df_aux

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [ ]:
# podemos utilizar o del para excluir colunas
del df_aux ['CPI']

KeyError: ignored

In [ ]:
df_aux.drop (0)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,Unemployment
1,1,12-02-2010,1641957.44,1,38.51,2.548,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,8.106
...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,8.667

In [ ]:
df_aux.drop([1,3], inplace = True)
df_aux

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,8.106
...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,8.667

In [ ]:
df_aux.drop(['Fuel_Price','Unemployment'], inplace = True, axis='columns')
df_aux

Dados   Store        Date  Weekly_Sales  Holiday_Flag  Temperature
Indice
0           1  05-02-2010    1643690.90             0        42.31
2           1  19-02-2010    1611968.17             0        39.93
4           1  05-03-2010    1554806.68             0        46.50
5           1  12-03-2010    1439541.59             0        57.79
6           1  19-03-2010    1472515.79             0        54.58
...       ...         ...           ...           ...          ...
6430       45  28-09-2012     713173.95             0        64.88
6431       45  05-10-2012     733455.07             0        64.89
6432       45  12-10-2012     734464.36             0        54.47
6433       45  19-10-2012     718125.53             0        56.47
6434       45  26-10-2012     760281.43             0        58.85

[6433 rows x 5 columns]

- podem ser add nomes para as lables das linhas e colunas

In [ ]:
df_aux.index.name = 'Indice'
df_aux.columns.name ='Dados'

In [ ]:
df_aux

Dados,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,Unemployment
Indice,,,,,,,
0,1,05-02-2010,1643690.90,0,42.31,2.572,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,8.106
...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,8.667

##reindexação

In [ ]:
obj = pd.Series([4.5,7,5,3], index =['d', 'b', 'c', 'a'])
obj

d    4.5
b    7.0
c    5.0
a    3.0
dtype: float64

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a    3.0
b    7.0
c    5.0
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['azul','roxo','amarelo'], index = [0,2,4])
obj3

0       azul
2       roxo
4    amarelo
dtype: object

In [ ]:
obj3.reindex(range(6))

0       azul
1        NaN
2       roxo
3        NaN
4    amarelo
5        NaN
dtype: object

- para dados ordenados , cpomo series temporais talvez seja desejavel fazer algum preenchimento ao realizar a reindexação. a opção method permite fazer esse preenchimento. ometodo ffill preenche para frente. o metodo bfill preenche como referencia valores para tras .

In [ ]:
obj3.reindex(range(6), method = 'ffill')

0       azul
1       azul
2       roxo
3       roxo
4    amarelo
5    amarelo
dtype: object

In [ ]:
obj3.reindex(range(6),method = 'bfill')

0       azul
1       roxo
2       roxo
3    amarelo
4    amarelo
5        NaN
dtype: object

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
array_criado = np.array([[0,1,2,3],[3,4,5]])
array_criado

<ipython-input-2-c63917f5df00>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_criado = np.array([[0,1,2,3],[3,4,5]])

array([list([0, 1, 2, 3]), list([3, 4, 5])], dtype=object)

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6]], columns = ['col1','col2','col3'])
df

   col1  col2  col3
0     1     2     3
1     4     5     6

In [ ]:
dados = {'flamengo':[56,72,90,71,71],'palmeiras':[63,80,74,58,66], 'corintia':[72,44,56,51,57]}
fut = pd.DataFrame(dados,index = [2017,2018,2019,2020,2021])
fut

      flamengo  palmeiras  corintia
2017        56         63        72
2018        72         80        44
2019        90         74        56
2020        71         58        51
2021        71         66        57

# criacao do projeto individual.

In [ ]:
proj = {'Dia':['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],'Horas Trabalhadas':[6,7,8,6,7,5,4],'Bugs Corrigidos':[3,2,1,4,3,2,1],'Tarefas Concluídas':[5,4,6,4,5,3,2]}
mod4 = pd.DataFrame(proj,index = [0,1,2,3,4,5,6])
mod4

       Dia  Horas Trabalhadas  Bugs Corrigidos  Tarefas Concluídas
0  Segunda                  6                3                   5
1    Terça                  7                2                   4
2   Quarta                  8                1                   6
3   Quinta                  6                4                   4
4    Sexta                  7                3                   5
5   Sábado                  5                2                   3
6  Domingo                  4                1                   2

In [ ]:
mod4.sum(axis='columns'['Horas Trabalhadas'])

<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<ipython-input-69-4880beb60692>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  mod4.sum(axis='columns'['Horas Trabalhadas'])

TypeError: ignored

#aula 25/07

##aplicando funçoes e mapeamento

In [ ]:
preco = 1000
def calcular_imposto(preco):
  return preco * 0.3
print(calcular_imposto(preco))

300.0

-exemplo de função lambda

In [ ]:
calcular_imposto2 = lambda x: x*0.3
calcular_imposto2(preco)

300.0

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
frame = pd.DataFrame (np.arange(9).reshape((3,3)),
                     index = ['a','b','c'],
                     columns = ['Ohio','Texas','California'])
frame

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [ ]:
f = lambda x: x.max()- x.min()
frame.apply(f)

Ohio          6
Texas         6
California    6
dtype: int64

In [ ]:
frame.apply(f,axis = 'columns')

a    2
b    2
c    2
dtype: int64

In [ ]:
#criar uma nova coluna
frame['total']= frame.apply(lambda x: x.sum(),axis = 'columns')
frame

   Ohio  Texas  California  total
a     0      1           2      3
b     3      4           5     12
c     6      7           8     21

#colocar uma categoria como sendo par ou impar.

In [ ]:
frame['categoria'] = frame['total'].apply(lambda x:'impar'if x%2 else'par')
frame

   Ohio  Texas  California  total categoria
a     0      1           2      3     impar
b     3      4           5     12       par
c     6      7           8     21     impar

In [ ]:
#
def f(x):
  return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)

     Ohio  Texas  California  total categoria
min     0      1           2      3     impar
max     6      7           8     21       par

- applymap

In [ ]:
numeros = pd.DataFrame(np.random.randn(4,3), columns=['a','b','c'],index =['c1','c2','c3','c4'])
numeros

           a         b         c
c1 -0.771923 -0.678132  0.208475
c2  1.175729 -1.310118 -0.511706
c3  0.542469 -1.930206  0.068292
c4  1.338606  0.137716 -0.051778

In [ ]:
format=lambda x:'%.2f'% x
numeros.applymap(format)

        a      b      c
c1  -0.77  -0.68   0.21
c2   1.18  -1.31  -0.51
c3   0.54  -1.93   0.07
c4   1.34   0.14  -0.05

####trocando as cores

In [ ]:
def color_df(valor):
  cor = 'red' if valor < 0 else 'blue'
  return 'color: ' + cor

numeros.style.applymap(color_df)

## ordenação e classificação

In [ ]:
obj = pd.Series(range(4),index = ['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index = ['three', 'one'],
                     columns = ['d', 'a', 'b', 'c'])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [ ]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
frame.sort_index(axis = 'columns',)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [ ]:
frame.sort_index(axis='columns', ascending = False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [ ]:
frame = pd.DataFrame({'b':[4,7,3,2],'a':[0,1,0,1]})
frame

   b  a
0  4  0
1  7  1
2  3  0
3  2  1

In [ ]:
frame.sort_values(by='a')

   b  a
0  4  0
2  3  0
1  7  1
3  2  1

In [ ]:
frame.sort_values(by=['a','b'])

   b  a
2  3  0
0  4  0
3  2  1
1  7  1

#Aula 26/07

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url='https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
titanic=pd.read_csv(url)
titanic

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [ ]:
titanic_filtro=titanic[[survived ]]

In [ ]:
format = lambda valor:'%%.2f' % valor
titanic_filtro['survived'].apply(format)

NameError: ignored

### media, moda e mediana .........

- relembrar

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#funçaõ lambda para somar dois valores
soma = lambda num1, num2: num1 + num2
soma(15,20)

35

In [ ]:
frame = pd.DataFrame(np.arange(10).reshape(5,2), columns = ['A','B'])
frame

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [ ]:
# funçao para calcular o quadrado de um numero
quadrado = lambda valor: valor*valor
frame['A'].apply(quadrado)

0     0
1     4
2    16
3    36
4    64
Name: A, dtype: int64

In [ ]:
#utilizar para todo dataframe
frame.applymap(quadrado)

    A   B
0   0   1
1   4   9
2  16  25
3  36  49
4  64  81

In [ ]:
 soma = lambda num:num.sum()
 frame.apply(soma)

A    20
B    25
dtype: int64

In [ ]:
frame.apply(soma,axis='columns')

0     1
1     5
2     9
3    13
4    17
dtype: int64

In [ ]:
#organizar os valores pelos index
frame.sort_index()

   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [ ]:
frame.sort_values(by = 'B', ascending= False)

   A  B
4  8  9
3  6  7
2  4  5
1  2  3
0  0  1

### estatistica , estatistica descritiva( media , moda , mediana )

### media

In [ ]:
# criar uma series para exemplo
exemplo_series = pd.Series([1,5,10,30,30,40,500])
exemplo_series

0      1
1      5
2     10
3     30
4     30
5     40
6    500
dtype: int64

In [ ]:
sum(exemplo_series)/len(exemplo_series)

88.0

In [ ]:
exemplo_series.mean()

88.0

In [ ]:
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
titanic = pd.read_csv(url)
titanic

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [ ]:
titanic['Age'].mean()

29.471443066516347

###moda

In [ ]:
exemplo_series.mode()

0    30
dtype: int64

In [ ]:
titanic['Age'].mode()

0    22.0
Name: Age, dtype: float64

## mediana

In [ ]:
exemplo_series.median()

30.0

In [ ]:
conjunto1 = pd.Series([3,5,4,7,9,5,2])
conjunto1

0    3
1    5
2    4
3    7
4    9
5    5
6    2
dtype: int64

In [ ]:
conjunto2 = pd.Series([1,2,3,4,4,5,1000])
conjunto2

0       1
1       2
2       3
3       4
4       4
5       5
6    1000
dtype: int64

In [ ]:
conjunto1.mean()

5.0

In [ ]:
conjunto2.mean()

145.57142857142858

In [ ]:
conjunto1.mode()

0    5
dtype: int64

In [ ]:
conjunto2.mode()

0    4
dtype: int64

In [ ]:
conjunto1.median()

5.0

In [ ]:
conjunto2.median()

4.0

#projeto

In [ ]:
import pandas as pd
import numpy as np

### Fazendo um relatório ja fornecido .

In [ ]:
proj = {'Dia':['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],'Horas Trabalhadas':[6,7,8,6,7,5,4],'Bugs Corrigidos':[3,2,1,4,3,2,1],'Tarefas Concluídas':[5,4,6,4,5,3,2]}
mod4 = pd.DataFrame(proj,index = [0,1,2,3,4,5,6])
mod4

       Dia  Horas Trabalhadas  Bugs Corrigidos  Tarefas Concluídas
0  Segunda                  6                3                   5
1    Terça                  7                2                   4
2   Quarta                  8                1                   6
3   Quinta                  6                4                   4
4    Sexta                  7                3                   5
5   Sábado                  5                2                   3
6  Domingo                  4                1                   2

#Fazendo o total de horas Trabalhadas .

In [ ]:
mod4['Horas Trabalhadas'].sum()

43

#Fazendo a media diaria de horas trabalhadas.

In [ ]:
mod4['Horas Trabalhadas'].describe()['mean']

6.142857142857143

#Fazendo o total de bugs corrigidos.

In [ ]:
mod4['Bugs Corrigidos'].sum()

16

#fazendo a media diaria de bugs corrigidos.

In [ ]:
mod4['Bugs Corrigidos'].describe()['mean']

2.2857142857142856

#Fazendo o total de tarefas concluidas.

In [ ]:
mod4['Tarefas Concluídas'].sum()

29

#Fazendo media diaria de tarefas concluidas.

In [ ]:
mod4['Tarefas Concluídas'].describe()['mean']

4.142857142857143

#produtividade diaria (tarefas concluidas por hora)

In [ ]:
mod4['Produtividade Diaria'] = mod4['Tarefas Concluídas'] / mod4['Horas Trabalhadas']
mod4

,Dia,Horas Trabalhadas,Bugs Corrigidos,Tarefas Concluídas,Produtividade Diaria
0,Segunda,6,3,5,0.833333
1,Terça,7,2,4,0.571429
2,Quarta,8,1,6,0.750000
3,Quinta,6,4,4,0.666667
4,Sexta,7,3,5,0.714286
5,Sábado,5,2,3,0.600000
6,Domingo,4,1,2,0.500000

In [ ]:
mod4['Produtividade Diaria'] = mod4['Produtividade Diaria'].round(2)
mod4

,Dia,Horas Trabalhadas,Bugs Corrigidos,Tarefas Concluídas,Produtividade Diaria
0,Segunda,6,3,5,0.83
1,Terça,7,2,4,0.57
2,Quarta,8,1,6,0.75
3,Quinta,6,4,4,0.67
4,Sexta,7,3,5,0.71
5,Sábado,5,2,3,0.60
6,Domingo,4,1,2,0.50